package Client;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrame.java
 *
 * Created on Dec 16, 2008, 11:08:15 PM
 */

//package client;

/**
 *
 * @author HUY CUONG
 */
import java.net.*;
import java.io.*;
import java.sql.*;
import java.util.*;
import java.lang.*;
public class Client extends javax.swing.JFrame {
public String commaytinh;
public String comtour;
public String comkhachsan;
public String comdichvu;
public String comphuongtien;
public String hovaten;
public String sohochieu;
public String scmnd;
public String dienthoai;
public String hochieu;
public String email;
public String sophong;
public String soghe;
public String lq;
public String diachi;
public String chonchucnangchuongtrinh;
    /** Creates new form JFrame */
    public Client() {
        initComponents();
        ketnoidulieu();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
		jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 20));
        jLabel17.setText("TRAVELING WELLCOME TO CENTER TOURIST THAI-VIET");
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setText("NHAP THONG TIN DANG KY TOUR");

        jLabel2.setText("Connection");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Server1", "Server2", "Server3", "Server4" }));

        jLabel3.setText("Name");

        jLabel4.setText("Address");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Phone");

        jLabel6.setText("Email");

        jLabel7.setText("Tour");

//        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DN-PN", "DN-HN", "DN-NT", "DN-SG" }));
        int dem=0;
		try{
//			 Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
			 String url3 = "jdbc:ucanaccess://F:\\Research\\Nguyen Ha Huy Cuong\\Server1\\TOUR.mdb";
			 Connection dbcn3 = DriverManager.getConnection(url3);
			 Statement dbst3 = dbcn3.createStatement();
			//j//Statement dbstP = dbcn3.createStatement();
     		 ResultSet rs3=null;
			 // ResultSet rsmaP=null;
	  		 rs3 = dbst3.executeQuery("select * from DangKy");
				Vector t3=new Vector();
				while (rs3.next()) {
					String tam3=rs3.getString(8);
					t3.addElement(tam3);
					dem=dem+1;
					}
			Enumeration e3=t3.elements();
			String[] MaDBtoComBo=new String[dem];//Tao bien chua so luong ma vung
			int k=0;
			while (e3.hasMoreElements())
			{
				String t32=(String)e3.nextElement();
				MaDBtoComBo[k]=t32;
				k+=1;
			}

			jComboBox2=new javax.swing.JComboBox(MaDBtoComBo);//Dua du lieu vao combo
		}catch(Exception e3){
			System.out.print(e3.getMessage());
		}
        jLabel8.setText("Hotle");

       // jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hoang Long", "Thang Loi", "Cong Doan", "Hai Van" }));
        int dem1=0;
		try{
			 //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver").newInstance();
			 String url4 = "jdbc:ucanaccess://F:\\Research\\Nguyen Ha Huy Cuong\\Server2\\TOUR.mdb";
			 Connection dbcn4 = DriverManager.getConnection(url4);
			 Statement dbst4 = dbcn4.createStatement();
			//j//Statement dbstP = dbcn3.createStatement();
     		 ResultSet rs4=null;
			 // ResultSet rsmaP=null;
	  		 rs4 = dbst4.executeQuery("select * from DangKy");
			Vector t4=new Vector();
			while (rs4.next()) {
				String tam4=rs4.getString(9);
				t4.addElement(tam4);
				dem1=dem1+1;
					}
			Enumeration e4=t4.elements();
			String[] MaDBtoComBo1=new String[dem];//Tao bien chua so luong ma vung
			int k1=0;
			while (e4.hasMoreElements())
			{
				String t33=(String)e4.nextElement();
				MaDBtoComBo1[k1]=t33;
				k1+=1;
			}

			jComboBox3=new javax.swing.JComboBox(MaDBtoComBo1);//Dua du lieu vao combo
		}catch(Exception e4){

		}
		jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Service");

        //jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tennis", "Taxi", "Dien Thoai", "Wifi" }));
 int dem2=0;
		try{
			 //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver").newInstance();
			 String url5 = "jdbc:ucanaccess://F:\\Research\\Nguyen Ha Huy Cuong\\Server3\\TOUR.mdb";
			 Connection dbcn5 = DriverManager.getConnection(url5);
			 Statement dbst5 = dbcn5.createStatement();
			//j//Statement dbstP = dbcn3.createStatement();
     		 ResultSet rs5=null;
			 // ResultSet rsmaP=null;
	  		 rs5 = dbst5.executeQuery("select * from DangKy");
			Vector t5=new Vector();
			while (rs5.next()) {
				String tam5=rs5.getString(10);
				t5.addElement(tam5);
				dem2=dem2+1;
					}
			Enumeration e5=t5.elements();
			String[] MaDBtoComBo2=new String[dem2];//Tao bien chua so luong ma vung
			int k2=0;
			while (e5.hasMoreElements())
			{
				String t34=(String)e5.nextElement();
				MaDBtoComBo2[k2]=t34;
				k2+=1;
			}

			jComboBox4=new javax.swing.JComboBox(MaDBtoComBo2);//Dua du lieu vao combo
		}catch(Exception e5){

		}
        jLabel10.setText("Number Room");

        jLabel11.setText("Vehicle");

       // jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tau Lua", "Hang Khong", "Xe Khach" }));
 int dem3=0;
		try{
			 //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver").newInstance();
			 String url6 = "jdbc:odbc:TOUR3";
			 Connection dbcn6 = DriverManager.getConnection(url6);
			 Statement dbst6 = dbcn6.createStatement();
			//j//Statement dbstP = dbcn3.createStatement();
     		 ResultSet rs6=null;
			 // ResultSet rsmaP=null;
	  		 rs6 = dbst6.executeQuery("select * from Dangky");
			Vector t6=new Vector();
			while (rs6.next()) {
				String tam6=rs6.getString(12);
				t6.addElement(tam6);
				dem3=dem3+1;
					}
			Enumeration e6=t6.elements();
			String[] MaDBtoComBo3=new String[dem3];//Tao bien chua so luong ma vung
			int k3=0;
			while (e6.hasMoreElements())
			{
				String t35=(String)e6.nextElement();
				MaDBtoComBo3[k3]=t35;
				k3+=1;
			}

			jComboBox5=new javax.swing.JComboBox(MaDBtoComBo3);//Dua du lieu vao combo
		}catch(Exception e6){
		}
        jLabel12.setText("Number Chair");

        jLabel13.setText(" CMND");

        jLabel14.setText("PassPort");

        jLabel16.setText("CHUC NANG CUA CT");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dang ky", "Xoa", "Cap Nhat" }));

        jButton1.setText("THUC HIEN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("THOAT CHUONG TRINH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(123, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                .addComponent(jLabel5))
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, 262, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jComboBox5, 0, 262, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jComboBox4, 0, 262, Short.MAX_VALUE)
                                .addComponent(jComboBox3, 0, 262, Short.MAX_VALUE)
                                .addComponent(jComboBox2, 0, 262, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(jComboBox6, 0, 262, Short.MAX_VALUE))
                            .addGap(34, 34, 34)
                            .addComponent(jButton1)
                            .addGap(27, 27, 27)
                            .addComponent(jButton2)
                            .addGap(63, 63, 63))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>
private void ketnoidulieu()
{
    int dem=0;
		try{
			 Class.forName("sun.jdbc.odbc.JdbcOdbcDriver").newInstance();
			 String url3 = "jdbc:odbc:TOUR1";
			 Connection dbcn3 = DriverManager.getConnection(url3);
			 Statement dbst3 = dbcn3.createStatement();
			//j//Statement dbstP = dbcn3.createStatement();
     		 ResultSet rs3=null;
			 // ResultSet rsmaP=null;
	  		 rs3 = dbst3.executeQuery("select * from TOUR");
			Vector t3=new Vector();
			while (rs3.next()) {
				String tam3=rs3.getString(1);
				t3.addElement(tam3);
				dem=dem+1;
					}
			Enumeration e3=t3.elements();
			String[] MaDBtoComBo=new String[dem];//Tao bien chua so luong ma vung
			int k=0;
			while (e3.hasMoreElements())
			{
				String t32=(String)e3.nextElement();
				MaDBtoComBo[k]=t32;
				k+=1;
			}

			jComboBox1=new javax.swing.JComboBox(MaDBtoComBo);//Dua du lieu vao combo
		}catch(Exception e3){

		}

}
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
         System.exit(0);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
       commaytinh=(String)jComboBox1.getSelectedItem();
		lq=(String)jComboBox6.getSelectedItem();
        comtour=(String)jComboBox2.getSelectedItem();
		comkhachsan=(String)jComboBox3.getSelectedItem();
		comdichvu=(String)jComboBox4.getSelectedItem();
		comphuongtien=(String)jComboBox5.getSelectedItem();
        hovaten=jTextField1.getText();
        sohochieu=jTextField8.getText();
        scmnd=jTextField7.getText();
        diachi=jTextField2.getText();
		dienthoai=jTextField3.getText();
		email=jTextField4.getText();
		sophong=jTextField5.getText();
		soghe=jTextField6.getText();
       // ct=jTextField4.getText();
        //comtour=jTextField5.getText();
        //jLabel8.setText(lq+mv+sdt+csh+ct+dc);
		chonchucnangchuongtrinh=(String)jComboBox6.getSelectedItem();
        if(commaytinh.equals("Server1"))
        {
        try
	{
		Client_Connect_2_Server client = new Client_Connect_2_Server("localhost",2001);
		client.requestServer();
		client.shutdown();
	}
	catch (Exception e1)
	{
		jLabel15.setText("Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i t\u1edbi server1!");}
        }
        else{
            if(commaytinh.equals("Server2")){
		try
		{
			Client_Connect_2_Server client = new
			Client_Connect_2_Server("localhost",2002);
		client.requestServer();
		client.shutdown();
		}
		catch (Exception e2)
		{jLabel15.setText("Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i t\u1edbi server2!");}}
            else{
                try
			{
				Client_Connect_2_Server client = new
			Client_Connect_2_Server("localhost",2003);
		client.requestServer();
		client.shutdown();
			}
			catch (Exception e3)
			{jLabel15.setText("Kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i t\u1edbi server3!");}
            }

        }

    }  

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }
    class Client_Connect_2_Server {
    Socket connection;
    DataOutputStream out;
    BufferedReader in;
    
    public Client_Connect_2_Server(String destination,int port)
	{
  		try
  		{
  			connection = new Socket(destination,port);
  			in = new BufferedReader(new
  			InputStreamReader(connection.getInputStream()));
  			out= new DataOutputStream(connection.getOutputStream());
  			//System.out.println("Connected to server at port 3456.");
            jLabel15.setText("\u0110\u00e3 k\u1ebft n\u1ed1i t\u1edbi c\u1ed5ng 3456.");
  		}
  		catch(Exception e)
  		{
  			jLabel15.setText("L\u1ed7i k\u1ebft n\u1ed1i \u0111\u1ebfn m\u00e1y ch\u1ee7:");
                        //System.out.println("Loi Ket noi den Server: "+e);
  		}
 	}
    
    public void requestServer()
	{
		BufferedReader keyboardInput = new BufferedReader(
                     new InputStreamReader(System.in));

        boolean finished=false;
        //do
        {
        	try
        	{

        		String thongdiep =lq+","+hovaten+","+scmnd+","+sohochieu+","+comtour+","+comkhachsan+","+dienthoai+","+email+","+comdichvu+","+sophong+","+soghe+","+comphuongtien;
        		out.writeBytes("@$0|000|145|Client|Send|1|123$$"+thongdiep+"$@");
        		out.write(13);
        		out.write(10);
        		out.flush();

        		int inByte;
        		System.out.print(thongdiep);
        		while ((inByte = in.read()) != '\n')
                            System.out.write(inByte);
        		//System.out.println();

        	}
        	catch(Exception e)
        	{
        		jLabel15.setText("L\u1ed7i y\u00eau c\u1ea7u m\u00e1y ch\u1ee7:");
        	}
        }
        //while(!finished);
     }

    public void shutdown()
 	{
  		try
  		{
    		connection.close();
    	}
    	catch(IOException ex)
    	{
    		jLabel15.setText("IO error closing socket");
    	}
    }
}


    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration

}
